kununu/nukleus

components/DropDown/index.scss
Adjust dropdown styling to hide link color and item heights
=> Fix dropdown styling

components/Tabs/index.scss, package.json
=> fix missing border in theme block in Tabs

components/index.js, components/utils.js, package.json
Added utils to exported modules
=> Added utils to exported modules

components/Choice/index.jsx, tests/Choice.test.jsx, tests/__snapshots__/Choice.test.jsx.snap
helper to add icon/extra style for Choice item
=> labelClass for Choice added

components/ToolTip/index.jsx, components/index.scss, package.json, tests/__snapshots__/ToolTip.test.jsx.snap
I added type="button" to the tooltip Button to prevent it becoming a submit button inside forms
=> Infolabel button type

components/Autocomplete/index.jsx, components/Choice/index.scss, components/Combobox/index.jsx, components/TextField/index.scss, docs/components/AutocompleteDocs/props-default.txt, docs/components/AutocompleteDocs/props-definition.txt, docs/components/ComboboxDocs/props-default.txt, docs/components/ComboboxDocs/props-definition.txt, package.json, playground/app.jsx, tests/Autocomplete.test.jsx, tests/Combobox.test.jsx, tests/__snapshots__/Autocomplete.test.jsx.snap, tests/__snapshots__/Combobox.test.jsx.snap, yarn.lock
- Added debounce to autocomplete and combobox
- Same Height Choice Options via css grid (works only in modern browsers)
- Styling Fixes for ToolTip Labels
=> Kuntech 1332

components/MultipleChoice/index.jsx, components/TextField/index.jsx, package.json, playground/app.jsx, tests/MultipleChoice.test.jsx, tests/__snapshots__/MultipleChoice.test.jsx.snap, tests/__snapshots__/TextField.test.jsx.snap
Just removes an undefined class inside TextField Element Labels
=> removed undefined class from textfield label

package.json
=> fix(package): update react-datepicker to version 0.51.0

components/Autocomplete/index.jsx, components/Button/index.jsx, components/Choice/index.jsx, components/Combobox/index.jsx, components/DatePicker/index.jsx, components/DropDown/index.jsx, components/Error/index.jsx, components/InfoBox/index.jsx, components/InfoLabel/index.jsx, components/InfoText/index.jsx, components/MultipleChoice/index.jsx, components/Notification/index.jsx, components/Paginator/index.jsx, components/Select/index.jsx, components/Stars/index.jsx, components/Table/index.jsx, components/Tabs/index.jsx, components/TextField/index.jsx, components/ToolTip/index.jsx, package.json
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
Still some warnings from using react-router, will disappear after this dependency is updated.
=> Fix warnings

components/Button/index.jsx, docs/components/ButtonDocs/props-default.txt, docs/components/ButtonDocs/props-definition.txt, package.json, tests/__snapshots__/Button.test.jsx.snap, yarn.lock
Added an htmlType prop to buttons to make it possible to supply button, submit or reset as a type
=> Button html type

README.md, components/index.js, docs/components/App/index.jsx, docs/components/ErrorDocs/example.txt, docs/components/ErrorDocs/index.jsx, docs/components/ErrorDocs/props-default.txt, docs/components/ErrorDocs/props-definition.txt, docs/index.jsx
=> Export error component

components/Autocomplete/index.jsx
Show error message even if no new props are received
=> Update autocomplete error logic

components/Button/index.jsx, docs/components/ButtonDocs/props-default.txt, package.json, tests/__snapshots__/Button.test.jsx.snap
As discussed last friday, I set the default value for buttons to submit. Since this is basically a breaking change, I updated the version to 8.0.0
=> Set default button htmlType to submit

components/index.scss, package.json, yarn.lock
Had to update the focus style for inputs, according to mockups
=> Updated focus style for textfields

components/InfoBox/index.jsx, components/ToolTip/index.jsx, docs/components/ToolTipDocs/props-definition.txt, package.json, tests/ToolTip.test.jsx, tests/__snapshots__/ToolTip.test.jsx.snap
I have to add object data (like HTML) into Tooltip content.
=> ToolTip content PropTypes update

components/Button/index.scss, main.scss, package.json, playground/app.jsx
Adapted primary button according the jira entry: https://jira.xing.hh/secure/RapidBoard.jspa?rapidView=711&view=detail&selectedIssue=KUNPRO-1358
more info in: https://docs.google.com/document/d/1UnD852JQI_theScvn_WAw96DW2nY9VfRJhjT2u68WdI/edit?ts=59b16a02#
=> decreased height of primary button and increased its padding

components/DropDown/index.jsx, package-lock.json, package.json, tests/__snapshots__/Modal.test.jsx.snap
In tablets, the dropdown does not work. The onClick is not triggered because the _isOpen_ is already false thus the anchor no longer exists. With the timeout of 100ms the anchor is removed after the onClick has been triggered.
=> Fix dropdown tablet

components/Stars/index.jsx, package-lock.json, package.json
When upgrading kununu to react 16 I have this error.
`Error: Uncaught [Error: Warning: Received `false` for a non-boolean attribute `htmlFor`.
If you want to write it to the DOM, pass a string instead: htmlFor="false" or htmlFor={value.toString()}.
If you used to conditionally omit it with htmlFor={condition && value}, pass htmlFor={condition ? value : undefined} instead.`
This PR aims to fix the issue.
When rendering the label instead of rendering `<label for="false">` renders `<label>`
=> Fix star warning

components/Choice/index.scss, package.json
=> Fix choice in IE11

components/Choice/index.scss, package.json
- Fixes a bug introduced by removing the supports.
=> Bug fix - extra border on choice

package.json, src/components/DatePicker/index.jsx, src/components/TextField/index.jsx
=> Add umlaute to highlight check

package.json, src/components/TextField/index.jsx
Adds more characters that are to be included in highlight check
=> Add Special Characters to Textarea highlight check
